# Arduino Make file. Refer to https://github.com/sudar/Arduino-Makefile
# NB version from debian is hopelessly outdated
# !!! Important. You have to use make ispload to upload when using ISP programmer
#ALTERNATE_CORE = tiny
#ALTERNATE_CORE_PATH = /usr/share/arduino/tiny
#ARDUINO_VAR_PATH = /usr/share/arduino/tiny/cores/tiny
#BOARDS_TXT = /usr/share/arduino/tiny/boards.txt
BOARD_TAG = uno
#ISP_PROG = usbtiny
ARDMK_DIR = /usr/share/arduino
ARDMK_PATH = /usr/bin
#PARSE_BOARD_OPTS = --boards_txt=$(BOARDS_TXT)
include $(ARDMK_DIR)/Arduino.mk